import Head from 'next/head'
import Image from 'next/image'
// import styles from '../styles/Home.module.css'
import Sidebar from '../components/Sidebar'
import Sidebar2 from '../components/Sidebar2'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Whatsaap</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/whatsaap.ico" />
      </Head>

      <Sidebar2 />

    </div>
  )
}
